# Site settings
title: 18F Agile BPA Labor Categories
description: > # this means to ignore newlines until "baseurl:"
  Learn more about 18F's Agile BPA Labor Categories.
baseurl: '/agile-labor-categories'

# Header
header:
  logo_text: 18F Agile Labor Categories
  logo_img: logo.svg

# Build settings
markdown: kramdown

# Collections
collections:
  positions:
    permalink: /positions/:title/
    output: true

#Defaults
defaults:
  - scope:
      type: positions
    values:
      layout: template/post
