# Site settings
title: 18F Hiring
description: > # this means to ignore newlines until "baseurl:"
  Welcome to 18F Hiring!
baseurl: '/hiring'

# Header
header:
  logo_text: Hiring @ 18F
  logo_img: logo.svg

# Build settings
markdown: kramdown

# Collections
collections:
  positions:
    permalink: /positions/:title/
    output: true

#Defaults
defaults:
  - scope:
      type: positions
    values:
      layout: template/post